name: agronex
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <8.1.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  get: ^4.6.6
  google_sign_in: ^6.2.1
  persistent_bottom_nav_bar: ^5.0.2
  cloud_firestore: ^5.1.0
  image_picker: ^0.8.4+4
  image: ^3.0.2
  firebase_storage: ^12.1.1
  flutter_gravatar: ^2.0.2
  image_cropper: ^7.1.0
  photo_view: ^0.15.0
  path_provider: ^2.1.3
  intl: ^0.17.0
  url_launcher: ^6.3.0
  emoji_picker_flutter: ^2.2.0
  dio: ^5.3.3
  google_mlkit_translation: ^0.3.0
  share_plus: ^8.0.0
  http: ^1.2.2
  file_picker: ^8.0.7
  open_file: ^3.4.4
  open_file_macos: ^0.0.1
  connectivity_plus: ^6.1.1
  awesome_dialog: ^3.1.1
  flutter_spinkit: ^5.1.0
  flutter_dotenv: ^5.0.2
  blurry_modal_progress_hud: ^1.0.3
  uuid: ^3.0.6
  animated_text_kit: ^4.2.2




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/google.png
    - assets/images/apple.png
    - assets/images/default_avatar.png
    - assets/images/arrow.png
    - assets/images/camera.png
    - assets/images/detectionlogo.png

